export const mainConstants = {
  WAIT_FOR_RESPONSE: 'WAIT_FOR_RESPONSE',
  REQUEST_FAILED: 'REQUEST_FAILED',

  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS'
};
